### ISSUE TITLE
Bootblock license

### ISSUE THREAD

**Issue by deplinenoise** [AxisOxy/Planet-Rocklobster#1]
It looks like your bootblock.asm is ripped from my track loader: https://github.com/deplinenoise/trackloader/

That's not mentioned anywhere in your source or binary distributions as far as I can tell, which is against the license of that code.

**Comment by AxisOxy** [comment]
Hey Dep,

You are ofcourse right. My bootblock is heavily based on yours. I was sure it was the one from Photon/Scoopex. Sorry for that. I add you to the readme.

Greetings from Axis/Oxyron

PS: I hope to see some asskicking new Amiga stuff from you soon...

**Comment by AxisOxy** [comment]
Fixed!
Added you to the readme, added your licence file and a comment with my changes to your bootblock source.

**Comment by deplinenoise** [comment]
Cheers!
